language: node_js
node_js:
  - 10
sudo: required
services:
  - docker

script:
  - yarn run lint
  - yarn run test

after_script:
  - bash <(curl -s https://codecov.io/bash) -f "tests/results/coverage-final.json"
